services:
  - type: web
    name: pi4-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend_app.wsgi:application
    autoDeploy: true
